In [1]:
# Including required python libraries used in this project
import numpy as np
import pandas as pd
import emoji

from keras.models import Sequential
from keras.layers import Dense, Input, Dropout, SimpleRNN,LSTM, Activation
from keras.utils import np_utils

import matplotlib.pyplot as plt

Using TensorFlow backend.


In [2]:
# reading train emoji and test emoji data which are attached in the repo
train = pd.read_csv('train_emoji.csv',header=None)
test = pd.read_csv('test_emoji.csv',header=None)

In [3]:
# Checking data by showing first 5 rows of the train data
train.head()

0  1   2     3
0           never talk to me again  3 NaN   NaN
1  I am proud of your achievements  2 NaN   NaN
2   It is the worst day in my life  3 NaN   NaN
3                 Miss you so much  0 NaN   [0]
4                     food is life  4 NaN   NaN

In [4]:
# Checking data by showing first 5 rows of the test data
test.head()

0  1
0             I want to eat\t  4
1         he did not answer\t  3
2            he got a raise\t  2
3      she got me a present\t  0
4  ha ha ha it was so funny\t  2

In [5]:
# Creating dictionary for some emoji's, consisting of key - number and value - emoji 
emoji_dict = { 0 : ":heart:", 1 : ":baseball:", 2 : ":smile:", 3 : ":disappointed:", 4 : ":fork_and_knife:"}

In [6]:
# Printing each emoji icon by emojizing each emoji
for ix in emoji_dict.keys():
    print (ix,end=" ")
    print (emoji.emojize(emoji_dict[ix], use_aliases=True))

0 ❤
1 ⚾
2 😄
3 😞
4 🍴


In [7]:
# Creating training and testing data
X_train = train[0]
Y_train = train[1]

X_test = test[0]
Y_test = test[1]

print (X_train.shape, Y_train.shape, X_test.shape, Y_test.shape)
print ("-------------------------")
print (X_train[0],Y_train[0])

(132,) (132,) (56,) (56,)
-------------------------
never talk to me again 3


In [8]:
# Splitting the train data from sentences to words
for ix in range(X_train.shape[0]):
    X_train[ix] = X_train[ix].split()

# Splitting the test data from sentences to words
for ix in range(X_test.shape[0]):
    X_test[ix] = X_test[ix].split()
    
# Converting labels into categorical form
Y_train = np_utils.to_categorical(Y_train)

/home/ambika/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/ambika/.local/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


In [9]:
# Now checking the above conversion by printing train and test data at 0th index
print (X_train[0],Y_train[0])

['never', 'talk', 'to', 'me', 'again'] [0. 0. 0. 1. 0.]


In [10]:
# To check maximum length of sentence in training data
np.unique(np.array([len(ix) for ix in X_train]) , return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 4,  5, 26, 35, 20, 21, 11,  5,  1,  4]))

In [11]:
# To check maximum length of senetence in testing data
np.unique(np.array([len(ix) for ix in X_test]) , return_counts=True)

(array([2, 3, 4, 5, 6, 7, 8]), array([ 3, 12, 16, 17,  3,  4,  1]))

In [13]:
# Creating  embeddings dictionary with key = word and value = list of words in glove vector
embeddings_index = {}

f = open('glove.6B.50d.txt')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

In [14]:
# Checking length of a particular word
embeddings_index["i"].shape

(50,)

In [15]:
from scipy import spatial
# Checking cosine similarity of words happy and sad
spatial.distance.cosine(embeddings_index["happy"], embeddings_index["sad"])

0.31093674898147583

In [16]:
# Checking cosine similarity of words India and Delhi
spatial.distance.cosine(embeddings_index["india"], embeddings_index["delhi"])

0.18572336435317993

In [17]:
# Checking cosine similarity of words france and paris
spatial.distance.cosine(embeddings_index["france"], embeddings_index["paris"])

0.19746702909469604

In [18]:
# Filling the embedding matrix
embedding_matrix_train = np.zeros((X_train.shape[0], 10, 50))
embedding_matrix_test = np.zeros((X_test.shape[0], 10, 50))

for ix in range(X_train.shape[0]):
    for ij in range(len(X_train[ix])):
        embedding_matrix_train[ix][ij] = embeddings_index[X_train[ix][ij].lower()]
        
for ix in range(X_test.shape[0]):
    for ij in range(len(X_test[ix])):
        embedding_matrix_test[ix][ij] = embeddings_index[X_test[ix][ij].lower()]        

In [19]:
print (embedding_matrix_train.shape, embedding_matrix_test.shape)

(132, 10, 50) (56, 10, 50)


# Training model

## - Using RNN

In [20]:
# A simple RNN network to classify the emoji class from an input Sentence

model = Sequential()
model.add(SimpleRNN(64, input_shape=(10,50), return_sequences=True))
model.add(Dropout(0.5))
model.add(SimpleRNN(64, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(5))
model.add(Activation('softmax'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 10, 64)            7360      
_________________________________________________________________
dropout_1 (Dropout)          (None, 10, 64)            0         
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (None, 64)                8256      
_________________________________________________________________
dropout_2 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 325       
_________________________________________________________________
activation_1 (Activation)    (None, 5)                 0         
Total params: 15,941
Trainable params: 15,941
Non-trainable params: 0
_________________________________________________________________


In [21]:
# Setting Loss and Optimiser for the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
# Training of the model and Setting hyperparameters for the model
hist = model.fit(embedding_matrix_train,Y_train,
                epochs = 50, batch_size=32,shuffle=True
                )

Epoch 1/50
132/132 [==============================] - 2s 15ms/step - loss: 1.9733 - acc: 0.1818
Epoch 2/50
132/132 [==============================] - 0s 368us/step - loss: 1.8078 - acc: 0.2273
Epoch 3/50
132/132 [==============================] - 0s 389us/step - loss: 1.8040 - acc: 0.2348
Epoch 4/50
132/132 [==============================] - 0s 416us/step - loss: 1.7699 - acc: 0.2652
Epoch 5/50
132/132 [==============================] - 0s 413us/step - loss: 1.4999 - acc: 0.3485
Epoch 6/50
132/132 [==============================] - 0s 336us/step - loss: 1.5025 - acc: 0.3939
Epoch 7/50
132/132 [==============================] - 0s 340us/step - loss: 1.4341 - acc: 0.4015
Epoch 8/50
132/132 [==============================] - 0s 369us/step - loss: 1.4411 - acc: 0.3485
Epoch 9/50
132/132 [==============================] - 0s 308us/step - loss: 1.3512 - acc: 0.5000
Epoch 10/50
132/132 [==============================] - 0s 402us/step - loss: 1.3387 - acc: 0.4621
Epoch 11/50
132/132 [=========

In [23]:
# Prediction of the trained model 
pred = model.predict_classes(embedding_matrix_test)

### ACCURACY

In [24]:
# Calculating the accuracy of the algorithm
float(sum(pred==Y_test))/embedding_matrix_test.shape[0]

0.6071428571428571

In [25]:
# Printing the sentences with the predicted and labled emoji
for ix in range(embedding_matrix_test.shape[0]):
    
    if pred[ix] != Y_test[ix]:
        print(ix)
        print (test[0][ix],end=" ")
        print (emoji.emojize(emoji_dict[pred[ix]], use_aliases=True),end=" ")
        print (emoji.emojize(emoji_dict[Y_test[ix]], use_aliases=True))

2
['he', 'got', 'a', 'raise'] 🍴 😄
5
['he', 'is', 'a', 'good', 'friend'] 😄 ❤
6
['I', 'am', 'upset'] 😄 ❤
7
['We', 'had', 'such', 'a', 'lovely', 'dinner', 'tonight'] 🍴 ❤
11
['work', 'is', 'hard'] 😄 😞
12
['This', 'girl', 'is', 'messing', 'with', 'me'] 😄 😞
13
['are', 'you', 'serious', 'ha', 'ha'] 😞 😄
16
['work', 'is', 'horrible'] 😄 😞
17
['Congratulation', 'for', 'having', 'a', 'baby'] 🍴 😄
18
['stop', 'messing', 'around'] 😄 😞
23
['she', 'is', 'a', 'bully'] ❤ 😞
25
['I', 'am', 'upset'] 😄 😞
26
['I', 'worked', 'during', 'my', 'birthday'] ❤ 😞
27
['My', 'grandmother', 'is', 'the', 'love', 'of', 'my', 'life'] 😞 ❤
29
['valentine', 'day', 'is', 'near'] 🍴 ❤
30
['I', 'miss', 'you', 'so', 'much'] 😞 ❤
39
['I', 'like', 'to', 'laugh'] ❤ 😄
41
['I', 'like', 'your', 'jacket'] ❤ 😄
46
['What', 'you', 'did', 'was', 'awesome'] 😞 😄
50
['yesterday', 'we', 'lost', 'again'] ⚾ 😞
51
['family', 'is', 'all', 'I', 'have'] 😞 ❤
55
['I', 'did', 'not', 'have', 'breakfast'] 🍴 😞


In [26]:
# Predicting for our random sentence
x = ['i', 'do', 'think','this', 'class', 'is', 'very', 'interesting']

x_ = np.zeros((1,10,50))

for ix in range(len(x)):
    x_[0][ix] = embeddings_index[x[ix].lower()]

In [27]:
model.predict_classes(x_)

array([3])

##  - Using LSTM

In [28]:
# A simple LSTM network
model = Sequential()
model.add(LSTM(128, input_shape=(10,50), return_sequences=True))
model.add(Dropout(0.5))
model.add(LSTM(128, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(5))
model.add(Activation('softmax'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 10, 128)           91648     
_________________________________________________________________
dropout_3 (Dropout)          (None, 10, 128)           0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dropout_4 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 645       
_________________________________________________________________
activation_2 (Activation)    (None, 5)                 0         
Total params: 223,877
Trainable params: 223,877
Non-trainable params: 0
_________________________________________________________________


In [29]:
# Setting Loss ,Optimiser for model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [30]:
# Training model
hist = model.fit(embedding_matrix_train,Y_train,
                epochs = 50, batch_size=32,shuffle=True
                )

Epoch 1/50
132/132 [==============================] - 1s 9ms/step - loss: 1.5926 - acc: 0.2348
Epoch 2/50
132/132 [==============================] - 0s 1ms/step - loss: 1.5371 - acc: 0.3485
Epoch 3/50
132/132 [==============================] - 0s 1ms/step - loss: 1.4919 - acc: 0.3409
Epoch 4/50
132/132 [==============================] - 0s 1ms/step - loss: 1.4429 - acc: 0.3939
Epoch 5/50
132/132 [==============================] - 0s 1ms/step - loss: 1.3951 - acc: 0.3939
Epoch 6/50
132/132 [==============================] - 0s 1ms/step - loss: 1.3285 - acc: 0.4621
Epoch 7/50
132/132 [==============================] - 0s 1ms/step - loss: 1.1927 - acc: 0.5606
Epoch 8/50
132/132 [==============================] - 0s 1ms/step - loss: 1.0565 - acc: 0.6288
Epoch 9/50
132/132 [==============================] - 0s 1ms/step - loss: 0.9396 - acc: 0.6515
Epoch 10/50
132/132 [==============================] - 0s 1ms/step - loss: 0.8589 - acc: 0.6667
Epoch 11/50
132/132 [============================

In [31]:
# Prediction of trained model
pred = model.predict_classes(embedding_matrix_test)

### ACCURACY

In [32]:
# Calculating accuracy / score  of the model
float(sum(pred==Y_test))/embedding_matrix_test.shape[0]

0.6964285714285714

In [33]:
# Printing the sentences with the predicted and the labelled emoji
for ix in range(embedding_matrix_test.shape[0]):
    
    if pred[ix] != Y_test[ix]:
        print(ix)
        print (test[0][ix],end=" ")
        print (emoji.emojize(emoji_dict[pred[ix]], use_aliases=True),end=" ")
        print (emoji.emojize(emoji_dict[Y_test[ix]], use_aliases=True))

2
['he', 'got', 'a', 'raise'] 😞 😄
5
['he', 'is', 'a', 'good', 'friend'] 😄 ❤
6
['I', 'am', 'upset'] 😞 ❤
7
['We', 'had', 'such', 'a', 'lovely', 'dinner', 'tonight'] 😄 ❤
12
['This', 'girl', 'is', 'messing', 'with', 'me'] ❤ 😞
13
['are', 'you', 'serious', 'ha', 'ha'] 😞 😄
21
['you', 'brighten', 'my', 'day'] ❤ 😄
26
['I', 'worked', 'during', 'my', 'birthday'] 😄 😞
28
['enjoy', 'your', 'break'] ⚾ 😄
29
['valentine', 'day', 'is', 'near'] 😄 ❤
32
['My', 'life', 'is', 'so', 'boring'] ❤ 😞
37
['I', 'am', 'starving'] 😞 🍴
41
['I', 'like', 'your', 'jacket'] ❤ 😄
48
['I', 'want', 'to', 'joke'] 😞 😄
49
['go', 'away'] ⚾ 😞
50
['yesterday', 'we', 'lost', 'again'] ⚾ 😞
55
['I', 'did', 'not', 'have', 'breakfast'] 🍴 😞
